### ISSUE TITLE
Mismatch link of github repository

### ISSUE THREAD

**Issue by bibekgaihre** [deiondz/shadcn-fullcalender#3]
![image](https://github.com/user-attachments/assets/539f5cac-761a-4a85-959e-3f230fc690df)

Currently the link of repository in main page is empty. 
<p className="text-sm">
          Feel free to contribute to the project by submitting a pull request or opening an issue on the <Link className=" text-blue-600 font-medium" href="">GitHub repository</Link>.
        </p>
Maybe you can update this.

**Comment by deiondz** [comment]
Thank you for pointing this out. Yes I will change this.
